name: build-exe

on:
  workflow_dispatch:
  push:
    tags: ["v*"]

jobs:
  win-exe:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build exe with PyInstaller
        shell: pwsh
        run: |
          pyinstaller --noconfirm --clean --onefile --windowed `
            --name FileTransferOne `
            --hidden-import=tkinterdnd2 `
            sendfile.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FileTransferOne-windows
          path: dist/FileTransferOne.exe
